const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://today-obs.line-scdn.net/0hoAkXekhDMG5WIRoRzD1POWx3MwFlTSNtMhdhbRVPblopEX4wbEIsAHUjZl94RncwP0R_DXYpK19zFXJrPkUs/w1200',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://today-obs.line-scdn.net/0h17U3Xt5zbhhoSnvRx_0RT1AcYmlbLHQRSi51LE9ONStNZi1PV3k9e0tJNTRNeCgbSHhyf0weZCwScyFPBg/w1200',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://www.champion-bio.com/upload/catalog_m/enL_catalog_22F08_6ynahrcf7y.webp',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://img.news.ebc.net.tw/EbcNews/news/2022/06/10/1654882528_91258.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://blog.imprentas.eu/wp-content/uploads/2020/06/hamburger-pecora.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://mycampcook.com/images/com_joomrecipe/217/cropped-20230219092222-How.To.Make.Bisquick.Rolled.Biscuits.in.The.Air.Fryer.1..protected.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://img.news.ebc.net.tw/EbcNews/news/2022/09/09/1662731140_59387.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://uc.udn.com.tw/photo/2024/11/14/draft/30904184.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'bison steak',
    category: 'dinner',
    price: 22.99,
    img: 'https://cdn2.ettoday.net/images/6213/d6213312.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
